name: Kaggle Submission

on:
  workflow_dispatch:
    inputs:
      wait_time:
        description: "Wait time (seconds) after submission"
        default: "90"
        required: true
      max_retries:
        description: "Maximum retries for checking score"
        default: "8"
        required: true
      retry_interval:
        description: "Time between retries (seconds)"
        default: "15"
        required: true
      competition_name:
        description: "Kaggle competition name"
        default: "surveillance-for-retail-stores"
        required: true
      track_file:
        description: "Track file name (leave empty for latest)"
        required: false
      face_file:
        description: "Face file name (leave empty for latest)"
        required: false

jobs:
  submit:
    runs-on: ubuntu-latest

    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Determine which Kaggle credentials to use based on actor
      - name: Set Kaggle credentials
        id: set_kaggle_creds
        run: |
          if [ "${{ github.actor }}" == "sayedgamal99" ]; then
            echo "KAGGLE_USERNAME=${{ secrets.KAGGLE_USERNAME_SAYED }}" >> $GITHUB_ENV
            echo "KAGGLE_KEY=${{ secrets.KAGGLE_KEY_SAYED }}" >> $GITHUB_ENV
          elif [ "${{ github.actor }}" == "youssef-yasser-ali" ]; then
            echo "KAGGLE_USERNAME=${{ secrets.KAGGLE_USERNAME_YOUSSEF }}" >> $GITHUB_ENV
            echo "KAGGLE_KEY=${{ secrets.KAGGLE_KEY_YOUSSEF }}" >> $GITHUB_ENV
          elif [ "${{ github.actor }}" == "A7medElsharkawy" ]; then
            echo "KAGGLE_USERNAME=${{ secrets.KAGGLE_USERNAME_SHARK }}" >> $GITHUB_ENV
            echo "KAGGLE_KEY=${{ secrets.KAGGLE_KEY_SHARK }}" >> $GITHUB_ENV
          else
            # Default or fallback credentials
            echo "KAGGLE_USERNAME=${{ secrets.KAGGLE_USER_NAME }}" >> $GITHUB_ENV
            echo "KAGGLE_KEY=${{ secrets.KAGGLE_API_KEY }}" >> $GITHUB_ENV
          fi

      - name: Create kaggle.json
        run: |
          mkdir -p ~/.kaggle
          echo "{\"username\":\"$KAGGLE_USERNAME\",\"key\":\"$KAGGLE_KEY\"}" > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json

      - name: Run submission pipeline
        run: |
          python -c "from utils.auto_submitter import run_submission_pipeline; run_submission_pipeline(
            wait_time=${{ github.event.inputs.wait_time }}, 
            max_retries=${{ github.event.inputs.max_retries }}, 
            retry_interval=${{ github.event.inputs.retry_interval }}, 
            competition_name='${{ github.event.inputs.competition_name }}',
            submitted_by='${{ github.actor }}',
            track_file='${{ github.event.inputs.track_file }}',
            face_file='${{ github.event.inputs.face_file }}'
          )"

      - name: Pull latest changes
        run: |
          git pull --rebase origin main || echo "Pull failed, continuing with push"

      - name: Commit results back to repository
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Add submission results from GitHub Action (by ${{ github.actor }})"
          file_pattern: "submissions/ experiments/"
          branch: main
          commit_user_name: "GitHub Action"
          commit_user_email: "action@github.com"